const {
  getClientByContact,
  getClientProductsByDomain,
  checkServiceStatus,
  createSupportTicket,
  resetCpanelPassword,
  sendEmailNotification
} = require('../services/passwordResetService');

/**
 * Handle password reset request
 */
async function handlePasswordReset(req, res) {
  try {
    const { contact, domain } = req.body;

    // Validate input
    if (!contact || !domain) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: contact (email/phone) and domain are required'
      });
    }

    console.log(`🔐 Password reset request for contact: ${contact}, domain: ${domain}`);

    // Step 1: Find client by email or phone
    console.log('📞 Step 1: Finding client...');
    const client = await getClientByContact(contact);
    
    if (!client) {
      return res.status(404).json({
        success: false,
        error: 'Client not found with the provided email or phone number'
      });
    }

    console.log(`✅ Client found: ${client.firstname} ${client.lastname} (ID: ${client.id})`);

    // Step 2: Get client's products/services for the specific domain
    console.log('🛍️ Step 2: Getting client products for domain...');
    const products = await getClientProductsByDomain(client.id, domain);
    
    if (!products || products.length === 0) {
      return res.status(404).json({
        success: false,
        error: `No hosting services found for domain "${domain}" under this client account`
      });
    }

    console.log(`📦 Found ${products.length} product(s) for domain ${domain}`);

    // Step 3: Find the service for the domain
    console.log('🔍 Step 3: Finding service for domain...');
    let matchedService = null;

    // Find service that matches the domain exactly
    matchedService = Array.isArray(products) 
      ? products.find(p => p.domain === domain)
      : (products.domain === domain ? products : null);

    if (!matchedService) {
      // If no exact match, try partial matching
      const productArray = Array.isArray(products) ? products : [products];
      matchedService = productArray.find(p => 
        p.domain && (p.domain.includes(domain) || domain.includes(p.domain))
      );
    }

    if (!matchedService) {
      return res.status(404).json({
        success: false,
        error: `No hosting service found for domain "${domain}"`,
        availableServices: Array.isArray(products) 
          ? products.map(p => ({
              id: p.id,
              name: p.name || p.productname,
              domain: p.domain,
              status: p.status
            }))
          : [{
              id: products.id,
              name: products.name || products.productname,
              domain: products.domain,
              status: products.status
            }]
      });
    }

    console.log(`✅ Service found: ${matchedService.name || matchedService.productname} (Service ID: ${matchedService.id})`);

    // Step 4: Check service status
    console.log('📊 Step 4: Checking service status...');
    const statusCheck = checkServiceStatus(matchedService);
    
    console.log(`📋 Service status: ${statusCheck.status} (Active: ${statusCheck.isActive}, Suspended: ${statusCheck.isSuspended})`);

    // Step 5: Handle suspended/terminated services
    if (statusCheck.needsTicket) {
      console.log('🎫 Step 5: Creating support ticket for suspended/terminated service...');
      
      const ticketSubject = `Password Reset Request - Service Suspended/Terminated`;
      const ticketMessage = `
Dear Support Team,

A password reset was requested for the following service, but it appears to be ${statusCheck.status}:

Service Details:
- Service ID: ${matchedService.id}
- Product: ${matchedService.name || matchedService.productname}
- Domain: ${matchedService.domain || domain}
- Status: ${statusCheck.status}

Client Details:
- Client ID: ${client.id}
- Name: ${client.firstname} ${client.lastname}
- Email: ${client.email}

Please review the service status and assist with reactivation if appropriate, then proceed with the password reset.

This ticket was automatically generated by the password reset system.
      `.trim();

      try {
        const ticket = await createSupportTicket(
          client.id,
          matchedService.id,
          ticketSubject,
          ticketMessage
        );

        return res.json({
          success: true,
          action: 'ticket_created',
          message: `Service is ${statusCheck.status}. A support ticket has been created for manual review.`,
          ticket: {
            id: ticket.id,
            tid: ticket.tid,
            subject: ticketSubject
          },
          service: {
            id: matchedService.id,
            name: matchedService.name || matchedService.productname,
            domain: matchedService.domain,
            status: statusCheck.status
          }
        });
      } catch (error) {
        return res.status(500).json({
          success: false,
          error: `Service is ${statusCheck.status} and ticket creation failed: ${error.message}`
        });
      }
    }

    // Step 6: Reset password for active service
    console.log('🔐 Step 6: Resetting cPanel password...');
    
    try {
      // Reset password using WHMCS ModuleChangePw API
      const resetResult = await resetCpanelPassword(matchedService.id);
      
      if (!resetResult.success) {
        throw new Error(resetResult.error || 'Password reset failed');
      }
      
      console.log('✅ Password reset successful');
      
      // Send email notification with new password information
      console.log('📧 Step 7: Sending email notification...');
      const emailResult = await sendEmailNotification(
        matchedService.id, 
        'Hosting Account - cPanel Login Email',
        {
          // Pass new password for email template
          cpanel_password: resetResult.newPassword,
          domain: domain
        }
      );

      const response = {
        success: true,
        action: 'password_reset',
        message: 'Password reset completed successfully',
        service: {
          id: matchedService.id,
          name: matchedService.name || matchedService.productname,
          domain: matchedService.domain,
          status: statusCheck.status
        },
        client: {
          id: client.id,
          name: `${client.firstname} ${client.lastname}`,
          email: client.email
        },
        passwordReset: {
          success: true,
          message: 'cPanel password reset successfully',
          serviceId: resetResult.serviceId,
          newPassword: resetResult.newPassword // Include for reference
        },
        emailNotification: {
          success: true,
          message: 'Login credentials email sent successfully'
        }
      };

      return res.json(response);

    } catch (error) {
      console.error('❌ Password reset process failed:', error.message);
      return res.status(500).json({
        success: false,
        error: `Password reset failed: ${error.message}`,
        service: {
          id: matchedService.id,
          name: matchedService.name || matchedService.productname,
          domain: matchedService.domain
        }
      });
    }

  } catch (error) {
    console.error('❌ Password reset request failed:', error.message);
    return res.status(500).json({
      success: false,
      error: `Password reset request failed: ${error.message}`
    });
  }
}

/**
 * Get available hosting services for a client
 */
async function getClientHostingServices(req, res) {
  try {
    const { contact } = req.query;

    if (!contact) {
      return res.status(400).json({
        success: false,
        error: 'Contact (email or phone) is required'
      });
    }

    // Find client
    const client = await getClientByContact(contact);
    
    if (!client) {
      return res.status(404).json({
        success: false,
        error: 'Client not found with the provided email or phone number'
      });
    }

    // Get all client's products (without domain filter)
    const { callWhmcsApi } = require('../services/passwordResetService');
    const result = await callWhmcsApi('GetClientsProducts', {
      clientid: client.id,
      limitnum: 100
    });
    
    const products = result.products?.product || [];
    
    const hostingServices = (Array.isArray(products) ? products : [products]).map(product => {
      const statusCheck = checkServiceStatus(product);
      return {
        id: product.id,
        pid: product.pid,
        name: product.name || product.productname,
        domain: product.domain,
        status: product.status,
        isActive: statusCheck.isActive,
        isSuspended: statusCheck.isSuspended,
        canResetPassword: statusCheck.isActive
      };
    });

    return res.json({
      success: true,
      client: {
        id: client.id,
        name: `${client.firstname} ${client.lastname}`,
        email: client.email
      },
      hostingServices
    });

  } catch (error) {
    console.error('Error getting client hosting services:', error.message);
    return res.status(500).json({
      success: false,
      error: `Failed to get hosting services: ${error.message}`
    });
  }
}

module.exports = {
  handlePasswordReset,
  getClientHostingServices
};